### ISSUE TITLE
Profile: Composition

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/gravitate-health#40]
1. [type](https://github.com/hl7-eu/gravitate-health/issues/StructureDefinition-Composition-uv-epi-definitions.html#Composition.type)
   1. should be fixed $spor#100000155538 ?
   2. should we use /ask for a LOINC code ?

2. [author](https://github.com/hl7-eu/gravitate-health/issues/StructureDefinition-Composition-uv-epi-definitions.html#Composition.author)
   1. should be restricted to Organization ? (i.e. the MAH)
3. Sections
   1. are those the only sections of interest ?
        1. section:whatIsIn  ePI What's in Section
        2. section:whatIsFor  ePI What's for Section
        3. section:toBeKnown  ePI to be known Section
        4. section:howToTake  How to take Section
        5. section:sideEffects  Side Effects Section
        6. section:howToStore  How to store Section
        7. section:otherInfos  other information Section
   2. are cardinalities correct ?
1.  section.code
    1. the used codes doesn't exist in SPOR (e.g. 100000155538-0)
    2. should we use SPR referential codes ?
    3. should we use /ask for LOINC codes ?
1.  section.entry
    1. determine which kind of resource should be referred in each section

**Comment by cander2** [comment]
**Type**
Bound to a value set like the Regulated Authorization. 

For EU, this would be Product Information Document Type (RMS List id 100000155531)

For US, this would be Document Type including Content of Labeling Type (LOINC OID: 2.16.840.1.113883.6.1)

**author**
Yes, restricted to MAH. Bound to value set for each region.
EU, fixed to OMS
US, fixed to Dun and Bradstreet (D-U-N-S Number OID: 1.3.6.1.4.1.519.1)

**Sections**
Think we should make all the sections 0..1 for now. 

Remembered that we have three different documents (or compositions). One for the SmPC, Patient Leaflet, and the package label. Should we create 
A) three different kinds of composition similar to clinical use? Each with their own head value sets
Or 
B) one composition and each section references the bound value sets for each region?

I’m leaning towards B since it sounds easier to manage. Thoughts?

Bound to a value set 
EU, not in SPOR yet but we can use RMS as a placeholder
US, Section Headings (LOINC OID: 2.16.840.1.113883.6.1)

**Section.code**
EMA shared the headings with us in an excel file but they’re not in SPOR yet. Can use RMS url as a placeholder for now.

US, they have all their headings in LOINC (see above).

**Section.entry**
No need for entry. Can remove that and add these instead:
1. Text
2. Ordered by 
3. Emptyreason
4. Section

**Comment by gcangioli** [comment]
> **Section.entry** No need for entry. Can remove that and add these instead:
> 
> 1. Text
> 2. Ordered by
> 3. Emptyreason
> 4. Section

we have to have entries, otherwise there is no way to have the resources in the Bundle....

**Comment by cander2** [comment]
This is the composition though. In the Composition.section.entry the entry is 0..*

Within an ePI composition's sections, there should not be any references to other resources. 

Should be like this:
 |-identifier
 |-status
 |-type
 |-date
 |-author
 |-title
 |-Section
    |--title
    |--code
    |--text
    |--orderedby
    |--emptyreason
    |--section (for sections within sections)

There might be a future use case for this but i'd rather we avoid that complication now.

**Comment by gcangioli** [comment]
The composition has been split in two a generic ePI composition (https://hl7-eu.github.io/gravitate-health/StructureDefinition-Composition-uv-epi.html) and one for a specific type for EMA (https://hl7-eu.github.io/gravitate-health/StructureDefinition-Composition-eu-leaflet.html).

In this version the first approval time is captured in the composition as the first attestation of the composition, other options could be evaluated in the future
